server.port=8080

spring.application.name=wow-profession-compagnon-backend

logging.level.fr.emeric.wowprofessioncompagnon=DEBUG

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/wow_profession_compagnon}
spring.datasource.username=${DB_USERNAME:wow_app}
spring.datasource.password=${DB_PASSWORD:wowpostgresql2026}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Blizzard OAuth
blizzard.client-id=${BLIZZARD_CLIENT_ID}
blizzard.client-secret=${BLIZZARD_CLIENT_SECRET}

# Blizzard API
blizzard.region=eu
blizzard.namespace=static-eu
blizzard.locale=fr_FR

blizzard.oauth-url=https://oauth.battle.net/token
blizzard.api-base-url=https://eu.api.blizzard.com